@InventoryAPI_HostAddress =http://localhost:5205

GET {{InventoryAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{InventoryAPI_HostAddress}}/Products/
Accept: application/json

###

GET {{InventoryAPI_HostAddress}}/Categories/
Accept: application/json